Traceback (most recent call last):
  File "/home/runner/work/qmlcourse/qmlcourse/.venv/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/home/runner/work/qmlcourse/qmlcourse/.venv/lib/python3.8/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/runner/work/qmlcourse/qmlcourse/.venv/lib/python3.8/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/runner/work/qmlcourse/qmlcourse/.venv/lib/python3.8/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/opt/hostedtoolcache/Python/3.8.14/x64/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/runner/work/qmlcourse/qmlcourse/.venv/lib/python3.8/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/home/runner/work/qmlcourse/qmlcourse/.venv/lib/python3.8/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/runner/work/qmlcourse/qmlcourse/.venv/lib/python3.8/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
g = nx.Graph(rand_adj)

pos = nx.drawing.layout.random_layout(g, seed=42)
nx.draw(g, pos=pos)
edge_weights = nx.get_edge_attributes(g, "weight")
nx.draw_networkx_edge_labels(g, pos=pos, edge_labels=edge_weights)
nx.draw_networkx_labels(g, pos=pos)

plt.show()
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mTypeError[0m                                 Traceback (most recent call last)
Input [0;32mIn [4][0m, in [0;36m<cell line: 4>[0;34m()[0m
[1;32m      1[0m g [38;5;241m=[39m nx[38;5;241m.[39mGraph(rand_adj)
[1;32m      3[0m pos [38;5;241m=[39m nx[38;5;241m.[39mdrawing[38;5;241m.[39mlayout[38;5;241m.[39mrandom_layout(g, seed[38;5;241m=[39m[38;5;241m42[39m)
[0;32m----> 4[0m [43mnx[49m[38;5;241;43m.[39;49m[43mdraw[49m[43m([49m[43mg[49m[43m,[49m[43m [49m[43mpos[49m[38;5;241;43m=[39;49m[43mpos[49m[43m)[49m
[1;32m      5[0m edge_weights [38;5;241m=[39m nx[38;5;241m.[39mget_edge_attributes(g, [38;5;124m"[39m[38;5;124mweight[39m[38;5;124m"[39m)
[1;32m      6[0m nx[38;5;241m.[39mdraw_networkx_edge_labels(g, pos[38;5;241m=[39mpos, edge_labels[38;5;241m=[39medge_weights)

File [0;32m~/work/qmlcourse/qmlcourse/.venv/lib/python3.8/site-packages/networkx/drawing/nx_pylab.py:113[0m, in [0;36mdraw[0;34m(G, pos, ax, **kwds)[0m
[1;32m    111[0m cf[38;5;241m.[39mset_facecolor([38;5;124m"[39m[38;5;124mw[39m[38;5;124m"[39m)
[1;32m    112[0m [38;5;28;01mif[39;00m ax [38;5;129;01mis[39;00m [38;5;28;01mNone[39;00m:
[0;32m--> 113[0m     [38;5;28;01mif[39;00m [43mcf[49m[38;5;241;43m.[39;49m[43m_axstack[49m[43m([49m[43m)[49m [38;5;129;01mis[39;00m [38;5;28;01mNone[39;00m:
[1;32m    114[0m         ax [38;5;241m=[39m cf[38;5;241m.[39madd_axes(([38;5;241m0[39m, [38;5;241m0[39m, [38;5;241m1[39m, [38;5;241m1[39m))
[1;32m    115[0m     [38;5;28;01melse[39;00m:

[0;31mTypeError[0m: '_AxesStack' object is not callable
TypeError: '_AxesStack' object is not callable

